# Cloud Build configuration with security and performance optimizations
steps:
  # Security: Vulnerability scanning
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running security scan..."
        # Build with BuildKit for better caching and security
        DOCKER_BUILDKIT=1 docker build \
          --cache-from gcr.io/$PROJECT_ID/shikhi-api:latest \
          -t gcr.io/$PROJECT_ID/shikhi-api:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/shikhi-api:latest \
          -f apps/api/Dockerfile \
          .
    timeout: 1200s # 20 minutes

  # Push both commit SHA and latest tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/shikhi-api']
    timeout: 600s # 10 minutes

  # Deploy with comprehensive configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy shikhi-api \
          --image gcr.io/$PROJECT_ID/shikhi-api:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --memory 2Gi \
          --cpu 1 \
          --concurrency 80 \
          --timeout 300s \
          --max-instances 100 \
          --min-instances 0 \
          --set-env-vars NODE_ENV=production,PORT=8080 \
          --execution-environment gen2 \
          --cpu-boost \
          --session-affinity
    timeout: 600s # 10 minutes

  # Health check verification
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for deployment to be ready..."
        sleep 60
        
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe shikhi-api --region=us-central1 --format='value(status.url)')
        
        # Health check with retries
        for i in {1..10}; do
          echo "Health check attempt $i..."
          if curl -f -m 30 "$SERVICE_URL/health"; then
            echo "✅ Deployment successful and healthy!"
            exit 0
          fi
          echo "⏳ Retrying in 30 seconds..."
          sleep 30
        done
        
        echo "❌ Deployment health check failed!"
        exit 1
    timeout: 900s # 15 minutes

# Performance and security options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitution_option: 'ALLOW_LOOSE'
  
# Timeouts
timeout: 3600s # 1 hour total timeout

# Substitutions for flexibility
substitutions:
  _SERVICE_NAME: 'shikhi-api'
  _REGION: 'us-central1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '100'